arqui/config/routes.rb
Rails.application.routes.draw do
  resources :logs, only: [:show, :index]
  root 'logs#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

arqui/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

arqui/app/models/log.rb
class Log < ApplicationRecord
end

arqui/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :create_log
  protect_from_forgery with: :exception

  private
    def create_log
      @log = Log.new( { log_ip: request.remote_ip.to_s, date: Time.now.to_s} )

      @log.save
    end
end

arqui/app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = Log.all
  end

  def show
    @logs = Log.all
  end
end

arqui/app/helpers/application_helper.rb
module ApplicationHelper
end

arqui/app/helpers/logs_helper.rb
module LogsHelper
end

arqui/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arqui</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

arqui/app/views/logs/index.html.erb
<h1>Todas las requests:</h1>

<ul>
  <% @logs.each do |log| %>
    <li>
      IP: <%= log.log_ip %> Date: <%= log.date %>
    </li>
  <% end %>
</ul>

arqui/app/views/logs/show.html.erb
<h1>Algunas request:</h1>

<ul>
  <% @logs[-11..-1].each do |log| %>
    <li>
      IP: <%= log.log_ip %> Date: <%= log.date %>
    </li>
  <% end %>

</ul>

<div>  <%= link_to 'Ver todos', logs_path%> </div>